modLoader="javafml"

loaderVersion="[40,)"

license="MIT"

[[mods]]

modId="pullback"

version="${file.jarVersion}"

displayName="Pullback"

logoFile="logo.png"

credits="SomeDom"

authors="SomeDom"

description='''
This mod adds exactly the opposite of the Knocback enchantment, Pullback!
Now you can make sure your enemies and foes cannot escape from your ragigng wraith!
'''

[[dependencies.pullback]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pullback]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
